package com.faturaocr.application.export;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum ExportFormat {
    XLSX("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "xlsx"),
    CSV("text/csv", "csv"),
    LOGO("application/xml", "xml"),
    MIKRO("text/plain; charset=windows-1254", "txt"),
    NETSIS("application/xml", "xml"),
    LUCA("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "xlsx");

    private final String contentType;
    private final String extension;

    // Constructor generated by @RequiredArgsConstructor

    public static ExportFormat fromString(String format) {
        for (ExportFormat f : values()) {
            if (f.name().equalsIgnoreCase(format)) {
                return f;
            }
        }
        throw new IllegalArgumentException("Desteklenmeyen format: " + format);
    }
}
