package com.faturaocr.infrastructure.alerting;

public enum AlertType {
    EXTRACTION_SERVICE_DOWN,
    ALL_LLM_FAILED,
    LLM_BUDGET_WARNING,
    LLM_BUDGET_EXCEEDED,
    LLM_DAILY_LIMIT,
    DATABASE_CONNECTION_POOL_EXHAUSTED,
    REDIS_CONNECTION_FAILURE,
    RABBITMQ_CONNECTION_FAILURE,
    HIGH_ERROR_RATE,
    DISK_SPACE_LOW,
    LOGIN_BRUTE_FORCE_DETECTED,
    DATABASE_BACKUP_FAILED
}
