ALTER TABLE invoices ALTER COLUMN invoice_number DROP NOT NULL;
ALTER TABLE invoices ALTER COLUMN invoice_date DROP NOT NULL;
ALTER TABLE invoices ALTER COLUMN supplier_name DROP NOT NULL;
ALTER TABLE invoices ALTER COLUMN total_amount DROP NOT NULL;
ALTER TABLE invoices ALTER COLUMN subtotal DROP NOT NULL;
ALTER TABLE invoices ALTER COLUMN tax_amount DROP NOT NULL;
